services:
  app:
    build: .
    image: llama-integration
    container_name: server
    command: fastapi dev app/main.py --host 0.0.0.0
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:alpine